#!/usr/bin/env node
/**
 * Generate a fresh VAPID keypair for Web Push, print it to stdout, and
 * append it to .env.backend.local if no TASKFLOW_VAPID_PUBLIC_KEY is
 * already set there. Production keys (e.g. on Render) should be set as
 * env vars on the host, not in this file.
 *
 * Usage:
 *   npm run vapid:generate
 */
import webpush from "web-push";
import { existsSync, readFileSync, appendFileSync } from "node:fs";
import { resolve } from "node:path";

const envPath = resolve(process.cwd(), ".env.backend.local");
const keys = webpush.generateVAPIDKeys();
const subject = process.env.TASKFLOW_PUBLIC_APP_URL
  ? `mailto:notifications@${new URL(process.env.TASKFLOW_PUBLIC_APP_URL).hostname}`
  : "mailto:notifications@example.com";

const block = [
  "",
  "# Web Push VAPID keys — generated by scripts/generate-vapid.mjs.",
  "# Keep these secret; .env.backend.local is gitignored.",
  "# Production deploys (Render etc.) should set these as host env vars,",
  "# not in this file.",
  `TASKFLOW_VAPID_PUBLIC_KEY=${keys.publicKey}`,
  `TASKFLOW_VAPID_PRIVATE_KEY=${keys.privateKey}`,
  `TASKFLOW_VAPID_SUBJECT=${subject}`,
  "",
].join("\n");

const existing = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
const hasPublic = /^TASKFLOW_VAPID_PUBLIC_KEY=/m.test(existing);

console.log("Generated VAPID keypair:");
console.log("");
console.log(`TASKFLOW_VAPID_PUBLIC_KEY=${keys.publicKey}`);
console.log(`TASKFLOW_VAPID_PRIVATE_KEY=${keys.privateKey}`);
console.log(`TASKFLOW_VAPID_SUBJECT=${subject}`);
console.log("");

if (hasPublic) {
  console.log(`Skipped writing to ${envPath} (TASKFLOW_VAPID_PUBLIC_KEY already set there).`);
  console.log("To rotate keys: remove the existing lines and re-run this script.");
} else {
  appendFileSync(envPath, block, { mode: 0o600 });
  console.log(`Wrote new keys to ${envPath}.`);
  console.log("Restart the backend (`npm run backend:dev`) so it picks them up.");
}

console.log("");
console.log("For production: paste the three values into your host's env config");
console.log("(e.g. Render → Environment → Add env var). Never commit these.");
